name: fruit_hub_dash_bord
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  image_picker: ^1.2.0
  path: ^1.9.1
  skeletonizer: ^2.1.0+1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
