name: fruit_hub_dash_bord
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
